# Generated by Django 3.1.7 on 2021-03-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_keeper', '0002_lognote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogNote',
            new_name='Notebook',
        ),
    ]
