# Generated by Django 3.1.7 on 2021-03-16 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note_keeper', '0003_auto_20210316_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='modify_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 15, 44, 12, 978877, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
    ]
