# Generated by Django 3.1.7 on 2021-03-26 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('acc_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Auc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.01)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiuts.user')),
            ],
        ),
    ]
