# Generated by Django 3.1.7 on 2021-03-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiuts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
    ]
