# Generated by Django 3.1.7 on 2021-03-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiuts', '0002_remove_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.01),
        ),
        migrations.DeleteModel(
            name='Auc',
        ),
    ]
