# Generated by Django 3.1.7 on 2021-03-28 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aiuts', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remark',
            field=models.CharField(default='No message', max_length=256),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='record_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 3, 19, 58, 392417, tzinfo=utc), primary_key=True, serialize=False, verbose_name='date recorded'),
        ),
    ]
