# Generated by Django 3.1.7 on 2021-03-28 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aiuts', '0005_auto_20210328_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='record_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 7, 16, 10, 15679, tzinfo=utc), verbose_name='date recorded'),
        ),
    ]
