# Generated by Django 3.1.7 on 2021-03-29 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aiuts', '0006_auto_20210328_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='record_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 11, 16, 35, 774989, tzinfo=utc), verbose_name='date recorded'),
        ),
    ]
