# Generated by Django 3.1.7 on 2021-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiuts', '0009_auto_20210329_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date recorded'),
        ),
    ]
